import Head from "next/head";
import styled from "@emotion/styled";

/* Ejemplo de un styled component */
const H1 = styled.h1`
  color: red;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <H1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </H1>
        <a href="/deportes">ir a deportes</a>
      </main>
    </div>
  );
}
